### ISSUE TITLE
Lỗi khi chạy: mvn verify

### ISSUE THREAD

**Issue by phamhiepst** [phamhiepst/webui-automation#1]
C:\Users\pquochiep\eclipse-workspace\autoTest>mvn verify
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< jp.fjp:autoTest >---------------------------
[INFO] Building Serenity project with JUnit and WebDriver 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ autoTest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\pquochiep\eclipse-workspace\autoTest\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ autoTest ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ autoTest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ autoTest ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ autoTest ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ autoTest ---
[INFO]
[INFO] --- maven-failsafe-plugin:2.22.1:integration-test (default) @ autoTest ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running jp.fjp.features.search.SearchByKeywordStory
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener -

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   /
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|

 News and tutorials at http://www.serenity-bdd.info
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport
 Learn Serenity BDD online at http://serenity-dojo.com
-------------------------------------------------------------------------------------

[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: Search by keyword story
8 22, 2019 2:29:03 ߑO org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
8 22, 2019 2:29:03 ߑO org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Instantiating driver
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Driver capabilities: Capabilities {acceptInsecureCerts: true, browserName: firefox, firefox_profile: org.openqa.selenium.firefox..., headless: false, loggingPrefs: org.openqa.selenium.logging..., marionette: true, moz:firefoxOptions: {}, platform: ANY, version: }
1566408544541   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\PQUOCH~1\\AppData\\Local\\Temp\\rust_mozprofile.dxX92AhYX2Pe"
1566408544883   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1566408544883   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1566408544883   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1566408544884   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1566408546547   Marionette      INFO    Listening on port 59622
1566408546653   Marionette      WARN    TLS certificate errors will be ignored for this session
8 22, 2019 2:29:06 ߑO org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener -
        __    _____ _____ ____ _____   ____   _    ____  ____  _____ ____
  _     \ \  |_   _| ____/ ___|_   _| |  _ \ / \  / ___|/ ___|| ____|  _ \
 (_)_____| |   | | |  _| \___ \ | |   | |_) / _ \ \___ \\___ \|  _| | | | |
  _|_____| |   | | | |___ ___) || |   |  __/ ___ \ ___) |___) | |___| |_| |
 (_)     | |   |_| |_____|____/ |_|   |_| /_/   \_\____/|____/|_____|____/
        /_/

TEST PASSED: Test outcome unavailable
----------------------------------------------------------------------------
1566408550003   Marionette      INFO    Stopped listening on port 59622
[Child 14228, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_1565706750/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 14228, Chrome_ChildThread] WARNING: pipe error: 109: fil[Parent 13420, Gecko_IOThread] WARNING: pipe error: 109: file z:/task_1565706750/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 11168, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_1565706750/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 11168[GPU 6416, Chrome_Ch
###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

ildThread] WARNING: p
###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 9.137 s <<< FAILURE! - in jp.fjp.features.search.SearchByKeywordStory
[ERROR] Test mechanism  Time elapsed: 0.157 s  <<< ERROR!
net.thucydides.core.requirements.CouldNotLoadRequirementsException

[ERROR] jp.fjp.features.search.SearchByKeywordStory  Time elapsed: 7.17 s  <<< ERROR!
net.thucydides.core.requirements.CouldNotLoadRequirementsException

[ERROR] Test mechanism  Time elapsed: 7.243 s  <<< ERROR!
net.thucydides.core.requirements.CouldNotLoadRequirementsException

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR] Test mechanism.Test mechanism
[ERROR]   Run 1: null
[ERROR]   Run 2: null
[INFO]
[ERROR]   SearchByKeywordStory.jp.fjp.features.search.SearchByKeywordStory  CouldNotLoadRequirements
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO]
[INFO]
[INFO] --- serenity-maven-plugin:2.0.70:aggregate (serenity-reports) @ autoTest ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/pquochiep/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.622 s
[INFO] Finished at: 2019-08-22T02:29:12+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.0.70:aggregate (serenity-reports) on project autoTest: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.0.70:aggregate failed: Unable to provision, see the following errors:
[ERROR]
[ERROR] 1) Error in custom provider, java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
[ERROR]   at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
[ERROR]   while locating net.thucydides.core.util.EnvironmentVariables
[ERROR]     for the 1st parameter of net.thucydides.core.configuration.SystemPropertiesConfiguration.<init>(SystemPropertiesConfiguration.java:68)
[ERROR]   while locating net.thucydides.core.configuration.SystemPropertiesConfiguration
[ERROR]   at net.thucydides.core.guice.ThucydidesModule.configure(ThucydidesModule.java:52)
[ERROR]   while locating net.thucydides.core.webdriver.Configuration
[ERROR]
[ERROR] 1 error: org.apache.commons.lang3.StringUtils
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

C:\Users\pquochiep\eclipse-workspace\autoTest>

**Comment by phamhiepst** [comment]
Lỗi này xảy ra do các maven repository bị conflict với nhau. Xóa hết các maven bị conflict là được. Tham khảo https://dzone.com/articles/solving-dependency-conflicts-in-maven

WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/pquochiep/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
